{% set name = "gpyconform" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gpyconform-{{ version }}.tar.gz
  sha256: 741f304bb35a65ecf5d7ef3a19b002e7b5363761cf20f70752f2cdb344ef4dad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - pytorch >=2.0
    - gpytorch ==1.12
    - linear_operator >=0.5.3
    - numpy

test:
  imports:
    - gpyconform
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/harrisp/GPyConform"
  summary: "Extends GPyTorch with Gaussian Process Regression Conformal Prediction"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE.txt"
  doc_url: "https://gpyconform.readthedocs.io/"
  dev_url: "https://github.com/harrisp/GPyConform"

extra:
  recipe-maintainers:
    - harrisp
